API_TITLE = "FastAPI-App"
API_DESCRIPTION = "A FastAPI template made by runetech with <3"
API_VERSION = "0.1.0"
OPENAPI_VERSION = "3.1.0"
JWT_PROCESSING_ALGORITHM: str = "HS256"
NOWPAYMENTS_API_BASE = "https://api.nowpayments.io/v1"
NOWPAYMENTS_PAYMENT_CURRENCY = "USD"
NOWPAYMENTS_FEE_PAID_BY_USER = True
